"""add browser_profiles

Revision ID: 592e7ae78c43
Revises: 09754a1b1b30
Create Date: 2026-09-09 09:50:08.004424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592e7ae78c43'
down_revision: Union[str, Sequence[str], None] = '09754a1b1b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browser_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('start_url', sa.String(length=500), nullable=False),
    sa.Column('last_login', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_profiles_created_at'), 'browser_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_browser_profiles_name'), 'browser_profiles', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_browser_profiles_name'), table_name='browser_profiles')
    op.drop_index(op.f('ix_browser_profiles_created_at'), table_name='browser_profiles')
    op.drop_table('browser_profiles')
    # ### end Alembic commands ###
